# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcfbe3669b4439b1fd322af8c8fff4ef8e67c717627af513cefbc98220c217c23175b631040df6fe6e48b2b75dd3da8224cf2b1eb34deb60aa8feaee785d6c9

test:
  secret_key_base: 05b28c29522834daf6fa072b2d731761cda9314e176c7b6f62d353835cdbc9d821f9cffb645ad9e9c9827ec5187831d6d8d21adb1657701e1b866bc67939210e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
