# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24452a89530782f631f6230c3a2eccf79f65a8edf0a51cf9e9fd25798f521cbea87d49a93dbdd06433c1d718a3f296520c60fd999dd14016e4ca654fd2b28fc3

test:
  secret_key_base: 043eec088aabcd30fc575fa669844b821170a253ad2cbda2d9550a8f9b89e3408064309061511d1fb5d5b53e655a0429e10dc4570a0a38762bb0698b137c0977

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
