# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159b9a6048c86beffe2af8fbce68c92ce4d13f7673a38cb5951b756826b4fe498a922797259daf559243103c032153b3b8c799a31924b7dd45451ab00f192a11

test:
  secret_key_base: d1284198a1aaa0b77a0ef4c89a9ef07761c6944cf38ffe691836e2ed7fe8f0927107976a44952dae2b480107cc95c176371c0f5617aa60e4151c4858fe0773da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
